FROM ubuntu

RUN apt update && apt-get install -y texlive-full language-pack-zh* language-pack-ja language-pack-ko fonts-arphic-ukai fonts-arphic-uming fonts-ipafont-mincho fonts-ipafont-gothic fonts-unfonts-core
