name: Docker Image Jupyter Notebook CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'simple_jupyter_notebook/*'
  pull_request:
    branches: [ master ]
    paths: 
      - 'simple_jupyter_notebook/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          path: simple_jupyter_notebook/
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: smilywhale
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{ secrets.dockerhub_token }}
          # Docker repository to tag the image with
          repository: smilywhale/simple_jupyter_notebook
          tags: latest
          push: true
